#!/usr/bin/env python3
"""
Generate lsp_builtins.h from primitive documentation comments.

Scans src/builtin/*.c for doc comments and produces a static array
of builtin names, signatures, and descriptions for the LSP server.
"""
import argparse
import pathlib
import re


def parse_args():
    parser = argparse.ArgumentParser(description="Generate lsp_builtins.h from primitive docs")
    parser.add_argument("source_dir", type=pathlib.Path)
    parser.add_argument("output", type=pathlib.Path)
    return parser.parse_args()


def escape(value: str) -> str:
    return value.replace("\\", "\\\\").replace("\"", "\\\"").replace("\n", "\\n")


def display_name(name: str) -> str:
    """Extract display name from doc comment name field.

    '+\\0plus' -> '+'
    'abs' -> 'abs'
    '#genrec' -> None (skip auxiliary)
    '__memoryindex' -> None (skip internal)
    """
    if name.startswith("__") or name.startswith("#") or name.startswith(" "):
        return None
    # If there's a \0, the part before it is the display name
    if "\\0" in name:
        return name.split("\\0")[0]
    return name


def main():
    args = parse_args()
    prim_dir = args.source_dir / "src" / "builtin"
    entries = []
    comment_re = re.compile(r"/\*\*(.*?)\*/", re.S)

    for c_path in sorted(prim_dir.glob("*.c")):
        text = c_path.read_text()
        for match in comment_re.finditer(text):
            block = match.group(1)
            lines = [line.rstrip() for line in block.splitlines()]
            while lines and not lines[0].strip():
                lines.pop(0)
            if not lines:
                continue
            header = lines[0]
            if not header.startswith("Q"):
                continue
            header_parts = header.split(":", 1)
            lhs = header_parts[0].strip()
            signature = header_parts[1].strip() if len(header_parts) > 1 else ""
            lhs_tokens = lhs.split()
            if len(lhs_tokens) < 4:
                continue
            _qcode, _flags, index, name = lhs_tokens[:4]
            try:
                order = int(index)
            except ValueError:
                continue

            dname = display_name(name)
            if dname is None:
                continue

            desc = "\n".join(lines[1:]).strip()
            # Strip marker tags
            desc = desc.replace("[NATIVE]", "").replace("[SESSION]", "").strip()

            entries.append({
                "index": order,
                "name": dname,
                "signature": signature,
                "desc": desc,
            })

    entries.sort(key=lambda item: item["index"])
    # Deduplicate by name (keep first occurrence)
    seen = set()
    unique = []
    for e in entries:
        if e["name"] not in seen:
            seen.add(e["name"])
            unique.append(e)
    entries = unique

    args.output.parent.mkdir(parents=True, exist_ok=True)
    with args.output.open("w") as f:
        f.write("/* Auto-generated by gen_lsp_builtins.py -- do not edit */\n")
        f.write("#ifndef LSP_BUILTINS_H\n")
        f.write("#define LSP_BUILTINS_H\n\n")
        f.write("typedef struct {\n")
        f.write("    const char *name;\n")
        f.write("    const char *signature;\n")
        f.write("    const char *description;\n")
        f.write("} LspBuiltin;\n\n")
        f.write(f"static const LspBuiltin lsp_builtins[] = {{\n")
        for entry in entries:
            f.write(f"    {{ \"{escape(entry['name'])}\", "
                    f"\"{escape(entry['signature'])}\", "
                    f"\"{escape(entry['desc'])}\" }},\n")
        f.write("};\n\n")
        f.write(f"#define LSP_BUILTINS_COUNT (sizeof(lsp_builtins) / sizeof(lsp_builtins[0]))\n\n")
        f.write("#endif /* LSP_BUILTINS_H */\n")


if __name__ == "__main__":
    main()
